/* Banchan Jib — product catalogue + business settings */

window.BJ_SETTINGS = {
  // ── fill these in with the real handles ──
  instagram: 'banchan_jib.bd',       // instagram.com/<handle>
  facebook: 'BanchanJib',            // facebook.com/<page>
  currency: 'BDT',
  tagline: 'Comfort in Every Side Dish',
};

window.BJ_PRODUCTS = [
  {
    id: 'geotjeori',
    slug: 'geotjeori',
    name: 'Geotjeori Cup',
    sub: 'Fresh Cabbage Kimchi',
    kr: '겉절이',
    krRead: 'geot-jeo-ri',
    price: 80,
    img: '/assets/img/geotjeori.jpg',
    imgSm: '/assets/img/geotjeori-sm.jpg',
    short: 'Crunchy, spicy, and garlic heavy — the perfect sidekick for a steaming hot bowl of ramen!',
    story: 'Geotjeori is kimchi at its youngest and liveliest — fresh cabbage tossed the same day, so it keeps its crunch and bright, garlicky heat. No long fermentation, no waiting. Just the loud, happy version of kimchi that wakes up a bowl of ramen or a plate of plain rice.',
    granny: 'I made this one a little spicy — have it with something warm, okay?',
    meter: { spice: 4, crunch: 5, garlic: 5 },
    tags: ['spicy', 'fresh', 'garlicky'],
    pairs: ['A steaming bowl of ramen', 'Fried eggs over rice', 'Instant noodles at 1am'],
    keeps: 'Best enjoyed within 5–7 days. Keep refrigerated — the flavour deepens each day.',
    accent: 'kimchi',
  },
  {
    id: 'dangeun',
    slug: 'dangeun-namul',
    name: 'Dangeun Namul Cup',
    sub: 'Seasoned Carrots',
    kr: '당근나물',
    krRead: 'dang-geun na-mul',
    price: 70,
    img: '/assets/img/dangeun.jpg',
    imgSm: '/assets/img/dangeun-sm.jpg',
    short: 'Sweet, earthy, toasted sesame. Brings a delightful crunch to any food!',
    story: 'Carrots, cut into little matchsticks and gently coaxed in sesame oil until they turn sweet and tender-crisp. A quiet dish that never asks for attention — but the table feels emptier without it. This is the banchan that makes everything else taste more like home.',
    granny: 'Carrots are good for your eyes. You look at screens all day, don’t you?',
    meter: { spice: 1, crunch: 4, garlic: 2 },
    tags: ['sweet', 'nutty', 'gentle'],
    pairs: ['Bibimbap bowls', 'Kimbap filling', 'Any lunchbox that needs colour'],
    keeps: 'Stays happy for 4–5 days refrigerated. Let it sit out a few minutes before eating.',
    accent: 'carrot',
  },
  {
    id: 'shigeumchi',
    slug: 'shigeumchi-namul',
    name: 'Shigeumchi Namul Cup',
    sub: 'Seasoned Spinach',
    kr: '시금치나물',
    krRead: 'shi-geum-chi na-mul',
    price: 100,
    img: '/assets/img/shigeumchi.jpg',
    imgSm: '/assets/img/shigeumchi-sm.jpg',
    short: 'Savoury, nutty, sesame-infused. Pair it with warm rice and our Geotjeori for a hearty meal!',
    story: 'Spinach blanched for just a breath, then dressed by hand with sesame oil, garlic and a whisper of soy. It’s the dish Korean mothers sneak onto every table — soft, savoury, and quietly nourishing. With warm rice and a little geotjeori, it becomes a whole meal.',
    granny: 'Greens first, then the spicy things. That’s the rule in my kitchen.',
    meter: { spice: 1, crunch: 2, garlic: 3 },
    tags: ['savoury', 'nutty', 'nourishing'],
    pairs: ['A bowl of warm rice', 'Our Geotjeori cup', 'Doenjang or miso soup'],
    keeps: 'Most delicious within 3–4 days. Keep refrigerated and eat it often.',
    accent: 'spinach',
  },
  {
    id: 'trio',
    slug: 'banchan-trio',
    name: 'The Banchan Trio',
    sub: '3-Cup Bundle Set',
    kr: '반찬 세트',
    krRead: 'banchan se-teu',
    price: 220,
    img: '/assets/img/trio.jpg',
    imgSm: '/assets/img/trio-sm.jpg',
    short: 'Not sure which one to order yet? Get the best of all three with our 3-cup bundle pack!',
    story: 'One cup of each: fresh geotjeori, sweet sesame carrots and savoury spinach. This is how a Korean table is meant to look — a little of everything, arranged around a warm bowl of rice. The full Banchan Jib experience, packed like a care package.',
    granny: 'I packed one of everything so you don’t have to choose. Eat well, okay?',
    meter: { spice: 3, crunch: 4, garlic: 4 },
    tags: ['bundle', 'best value', 'full table'],
    pairs: ['A pot of fresh rice', 'Sharing with a friend', 'Meal-prep for a busy week'],
    keeps: 'Each cup keeps 3–7 days refrigerated. The kimchi only gets wiser with age.',
    accent: 'trio',
  },
];

window.BJ_BY_ID = Object.fromEntries(window.BJ_PRODUCTS.map(p => [p.id, p]));
